spring:
  application:
    name: appointment-platform
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ap}
    username: ${DB_USERNAME:ap}
    password: ${DB_PASSWORD:ap}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate